TAK-28 pycon taiwan 2024
takanory/slides pull request #112
Opened 2024-09-01 10:02 UTC by takanory

2024-09-13 02:39 UTC, terapyon reviewed
日本語の難しさのところの流れは良いと思います。
（US LTを丁寧にした感じですよね？）
台湾での講演を考えると、英語と台湾語を理解している人がメインだと思うので、日本語のことも対象知っていると思うと思う。

2024-09-13 02:39 UTC, terapyon commented on slides/20240921pycontw/index.md
> +## {fab}`python` Python supports Japanese leaning
このタイトルは、次のページからはじまる、HTML仕様のrubyと合わないと思う。
ここは、W3Cが定めている便利なものがあるとかかな。
「HTML Ruby Markup Extensions」
https://www.w3.org/TR/html-ruby-extensions/

2024-09-13 02:39 UTC, terapyon commented on slides/20240921pycontw/index.md
> +<ruby><ruby>パイソン<rt>pa i so n</rt></ruby>
ここは、意味のある言葉にしたい。

2024-09-13 02:39 UTC, terapyon commented on slides/20240921pycontw/index.md
> +</ruby>
ここも意味のある言葉にしたい。
「Pythonイベントは日曜日」とかはどうかな？
かたかなで、Pythonを示す「パイソン」はなくても良いかも。

2024-09-13 02:39 UTC, terapyon commented on slides/20240921pycontw/index.md
> +![Ikebukuro station](images/ikebukuro.jpg)
この写真いいですね。

2024-09-18 01:20 UTC, terapyon commented
再度流れはみました。流れはできていると思いますが、最後のまとめで何かがほしいところです。
（昨日、直接話もしましたが）
音声で読み上げる説明とデモを入れて、日本語学習を助けるというのはどうでしょうか？

2024-09-18 01:22 UTC, takanory commented
最後に「なんとなく読めそうだけどどう発音するかわからない」→Amazon Pollyで読み上げパートを追加する
で、まとめとしていくつかのライブラリとかAPIの使い方で日本語の勉強のサポートになるかも。

みたいに話をまとめる

appendixで品詞、原形についてやるかなぁ、まぁ軽く読み練習してから考えるか

2024-09-20 10:15 UTC, tkoyama010 requested changes
レビューしました。最後に音声が出来上がるのが素晴らしいです。トークがんばってください。

2024-09-20 10:15 UTC, tkoyama010 commented on README.rst
> +     * `Slides <https://slides.takanory.net/slides/20240921pycontw>`__
このリンクに行くと以下のような表示になります。おま環かもしれませんが念のため。
![image](https://github.com/user-attachments/assets/665a0e46-29eb-466b-8079-923566e8312b)

2024-09-20 10:15 UTC, tkoyama010 commented on slides/20240921pycontw/index.md
> +* **English talks** are available
すでにプロポーザルは締め切っているので以下の方が正しいかもしれません。
```suggestion
* **English talks** are there
```

2024-09-20 10:15 UTC, tkoyama010 commented on slides/20240921pycontw/index.md
> +
おそらく誤解する人も多いので一言断っておくとよいと思います。
```suggestion

* It not programming language Ruby.
```

2024-09-20 10:15 UTC, tkoyama010 commented on slides/20240921pycontw/index.md
> +* ローマ字に変換してひらがなを勉強しよう
翻訳もれでしょうか？適当に訳しました。
```suggestion
* Writing in the alphabet to represent the Japanese reading
* They use roman letters for place names and signs.
* Let's convert to romaji and study hiragana!
```

2024-09-20 10:15 UTC, tkoyama010 commented on slides/20240921pycontw/index.md
> +  * ここではcoreを使用
同じく適当な訳。
```suggestion
* Made with Rust, so it's fast
* There are multiple dictionaries.(small, core, full)
  * We use core here.
```

2024-09-20 10:15 UTC, tkoyama010 commented on slides/20240921pycontw/index.md
> +* ひらがなが読めない？
```suggestion
* We'll split the words based on the dictionary data.
* Can't read hiragana?
```

2024-09-20 13:11 UTC, takanory commented on README.rst
> +     * `Slides <https://slides.takanory.net/slides/20240921pycontw>`__
これはmerge前なので問題ないです

2024-09-20 13:13 UTC, takanory commented on slides/20240921pycontw/index.md
> +* **English talks** are available
たしかに。There are English talksにした

2024-09-20 13:16 UTC, takanory commented on slides/20240921pycontw/index.md
> +<ruby>日曜日<rt>nichi you bi</rt></ruby>、<ruby>前日<rt>zen jitsu</rt></ruby>
ママで

2024-09-20 13:18 UTC, takanory commented on slides/20240921pycontw/index.md
> +* ローマ字に変換してひらがなを勉強しよう
まだ最後までできてなかった。ありがとうございます。参考にさせてもらいます

2024-09-21 04:00 UTC, merged